//! Benchmarks for `BddBase`: end-to-end factoring + per-op allocation.
//!
//! Uses [`divan`](https://crates.io/crates/divan). With the `AllocProfiler`
//! global allocator, every bench also reports allocation bytes/count per
//! iteration — useful for catching silent allocation regressions in
//! `BddBase::{ite, and, xor}`.
//!
//! Run with:
//! ```text
//! cargo bench                            # run everything
//! cargo bench -- tiny                    # filter by name
//! cargo bench -- ops::                   # just the per-op allocation bench
//! cargo bench -- --sample-count 30       # override sample count
//! ```

use bex::{Base, BddBase, NID, ast::ASTBase, int::GBASE, solve::find_factors};

#[global_allocator]
static ALLOC: divan::AllocProfiler = divan::AllocProfiler::system();

fn main() { divan::main(); }


// --- end-to-end factoring benches ----------------------------------------
//
// `X4`, `X8`, `X16`, ... are distinct types generated by `xint_type!`, so
// divan's runtime `args = [...]` can't sweep them directly. A tiny macro
// emits one `#[divan::bench]` per row, giving a readable size table while
// keeping each variant independently filterable and configurable.

macro_rules! factor_benches {
  ( $( $name:ident : $a:ty, $b:ty => $n:expr, $expected:expr ; samples = $s:expr ),* $(,)? ) => {
    $(
      #[divan::bench(sample_count = $s)]
      fn $name(bencher: divan::Bencher) {
        bencher.bench_local(|| {
          find_factors::<$a, $b, BddBase>(&mut BddBase::new(), $n, $expected);
          GBASE.with(|gb| gb.replace(ASTBase::empty()));
        });
      }
    )*
  };
}

use bex::int::{X4, X8, X16};
factor_benches! {
  tiny  : X4, X8  =>  210, vec![(14, 15)]                         ; samples = 20,
  small : X8, X16 =>  210, vec![(1,210), (2,105), (3, 70), (5,42),
                                (6, 35), (7, 30), (10,21), (14,15)] ; samples = 10,
  // medium: X16, X32 => 2310, vec![/* ... */]                     ; samples = 3,
}


// --- per-op allocation benches -------------------------------------------
//
// These reduce a chain of N input variables via `ite` / `and` / `xor` on a
// fresh `BddBase`. Divan's `AllocProfiler` reports bytes and count of heap
// allocations for exactly the reduction body — `BddBase::new()` setup lives
// in `with_inputs` (excluded), and `bench_refs` keeps the `BddBase` drop
// outside the measured region too.

mod ops {
  use super::*;

  fn vars(n: u32) -> Vec<NID> { (0..n).map(NID::var).collect() }

  /// Left-fold N variables via `and`: (((v0 & v1) & v2) & ...).
  #[divan::bench(args = [8, 16, 32])]
  fn and_chain(bencher: divan::Bencher, n: u32) {
    bencher
      .with_inputs(|| (BddBase::new(), vars(n)))
      .bench_refs(|(bdd, vs)| {
        let mut acc = vs[0];
        for &v in &vs[1..] { acc = bdd.and(acc, v); }
        acc
      });
  }

  /// Left-fold N variables via `xor`: v0 ^ v1 ^ v2 ^ ...
  #[divan::bench(args = [8, 16, 32])]
  fn xor_chain(bencher: divan::Bencher, n: u32) {
    bencher
      .with_inputs(|| (BddBase::new(), vars(n)))
      .bench_refs(|(bdd, vs)| {
        let mut acc = vs[0];
        for &v in &vs[1..] { acc = bdd.xor(acc, v); }
        acc
      });
  }

  /// Nested if-then-else: ite(v0, ite(v1, ... , O), !acc).
  /// Neither the T nor E arm is a constant, so we exercise the full
  /// three-way normalization path of `BddBase::ite`.
  #[divan::bench(args = [8, 16, 32])]
  fn ite_chain(bencher: divan::Bencher, n: u32) {
    bencher
      .with_inputs(|| (BddBase::new(), vars(n)))
      .bench_refs(|(bdd, vs)| {
        let mut acc = vs[n as usize - 1];
        for i in (0..n as usize - 1).rev() {
          acc = bdd.ite(vs[i], acc, !acc);
        }
        acc
      });
  }
}
