//! C FFI bindings for bex. Exposes `BddBase`, `ASTBase`, and `SwapSolver`
//! to C/C++ callers; headers are generated by cbindgen. Used by the
//! external bdd-benchmark adapter at `tangentforks/bdd-benchmark`.
extern crate bex as bex_rs;
use bex_rs::{Base, BddBase, ast::ASTBase, swap::SwapSolver, nid::{NID, I, O}, vid::VID};
use std::panic::{AssertUnwindSafe, catch_unwind};
use std::sync::{Arc, Mutex};

macro_rules! bex_bdd_op_body {
    ($bdd:ident, $method:ident, $($param:ident),*) => {
        with_bdd_mut($bdd, |base| {
            $(let $param = NID::_from_u64($param.nid);)*
            bex_nid_t { nid: base.$method($($param),*)._to_u64() }
        })
    };
}

macro_rules! bex_ast_op_body {
    ($ast:ident, $method:ident, $($param:ident),*) => {
        with_ast_mut($ast, |base| {
            $(let $param = NID::_from_u64($param.nid);)*
            bex_nid_t { nid: base.$method($($param),*)._to_u64() }
        })
    };
}


#[repr(C)]
pub struct bex_bdd_t {
    base: *mut std::ffi::c_void,
}

#[repr(C)]
pub struct bex_ast_t {
    base: *mut std::ffi::c_void,
}

#[repr(C)]
pub struct bex_swap_t {
    base: *mut std::ffi::c_void,
}

#[repr(C)]
pub struct bex_nid_t {
    nid: u64,
}

#[repr(C)]
pub struct bex_vid_t {
    vid: u32,
}

fn ffi_nid_default() -> bex_nid_t {
    bex_nid_t { nid: O._to_u64() }
}

fn ffi_u64_default() -> u64 { 0 }

fn ffi_bool_default() -> bool { false }

fn ffi_usize_default() -> usize { 0 }

fn ffi_guard<T, F>(default: T, f: F) -> T
where
    F: FnOnce() -> T,
{
    catch_unwind(AssertUnwindSafe(f)).unwrap_or(default)
}

fn with_bdd_mut<F>(bdd: *mut bex_bdd_t, f: F) -> bex_nid_t
where
    F: FnOnce(&mut BddBase) -> bex_nid_t,
{
    ffi_guard(ffi_nid_default(), move || unsafe {
        let Some(bdd_ref) = bdd.as_ref() else { return ffi_nid_default() };
        let base_ptr = bdd_ref.base as *mut Arc<Mutex<BddBase>>;
        let Some(base_arc) = base_ptr.as_ref() else { return ffi_nid_default() };
        let Ok(mut base) = base_arc.lock() else { return ffi_nid_default() };
        f(&mut base)
    })
}

fn with_bdd_ref<F, R>(bdd: *mut bex_bdd_t, default: R, f: F) -> R
where
    F: FnOnce(&BddBase) -> R,
    R: Copy,
{
    ffi_guard(default, move || unsafe {
        let Some(bdd_ref) = bdd.as_ref() else { return default };
        let base_ptr = bdd_ref.base as *mut Arc<Mutex<BddBase>>;
        let Some(base_arc) = base_ptr.as_ref() else { return default };
        let Ok(base) = base_arc.lock() else { return default };
        f(&base)
    })
}

fn with_ast_mut<F>(ast: *mut bex_ast_t, f: F) -> bex_nid_t
where
    F: FnOnce(&mut ASTBase) -> bex_nid_t,
{
    ffi_guard(ffi_nid_default(), move || unsafe {
        let Some(ast_ref) = ast.as_ref() else { return ffi_nid_default() };
        let base_ptr = ast_ref.base as *mut Arc<Mutex<ASTBase>>;
        let Some(base_arc) = base_ptr.as_ref() else { return ffi_nid_default() };
        let Ok(mut base) = base_arc.lock() else { return ffi_nid_default() };
        f(&mut base)
    })
}

fn with_ast_ref<F, R>(ast: *mut bex_ast_t, default: R, f: F) -> R
where
    F: FnOnce(&ASTBase) -> R,
    R: Copy,
{
    ffi_guard(default, move || unsafe {
        let Some(ast_ref) = ast.as_ref() else { return default };
        let base_ptr = ast_ref.base as *mut Arc<Mutex<ASTBase>>;
        let Some(base_arc) = base_ptr.as_ref() else { return default };
        let Ok(base) = base_arc.lock() else { return default };
        f(&base)
    })
}

#[no_mangle]
pub extern "C" fn bex_bdd_new() -> *mut bex_bdd_t {
    let base = Box::into_raw(Box::new(Arc::new(Mutex::new(BddBase::new()))));
    Box::into_raw(Box::new(bex_bdd_t {
        base: base as *mut std::ffi::c_void,
    }))
}

/// Opt into direct single-threaded ITE recursion for this BDD base.
/// Best for bottom-up workloads; avoids swarm dispatch overhead.
#[no_mangle]
pub extern "C" fn bex_bdd_set_direct_ite(bdd: *mut bex_bdd_t, on: bool) {
    ffi_guard((), move || unsafe {
        let Some(bdd_ref) = bdd.as_ref() else { return };
        let base_ptr = bdd_ref.base as *mut Arc<Mutex<BddBase>>;
        let Some(base_arc) = base_ptr.as_ref() else { return };
        let Ok(mut base) = base_arc.lock() else { return };
        base.set_direct_ite(on);
    })
}

#[no_mangle]
pub extern "C" fn bex_bdd_free(bdd: *mut bex_bdd_t) {
    if !bdd.is_null() {
        unsafe {
            let base_ptr = (*bdd).base as *mut Arc<Mutex<BddBase>>;
            drop(Box::from_raw(base_ptr));
            drop(Box::from_raw(bdd));
        }
    }
}

#[no_mangle]
pub extern "C" fn bex_ast_new() -> *mut bex_ast_t {
    let base = Box::into_raw(Box::new(Arc::new(Mutex::new(ASTBase::new()))));
    Box::into_raw(Box::new(bex_ast_t {
        base: base as *mut std::ffi::c_void,
    }))
}

#[no_mangle]
pub extern "C" fn bex_ast_free(ast: *mut bex_ast_t) {
    if !ast.is_null() {
        unsafe {
            let base_ptr = (*ast).base as *mut Arc<Mutex<ASTBase>>;
            drop(Box::from_raw(base_ptr));
            drop(Box::from_raw(ast));
        }
    }
}

#[no_mangle]
pub extern "C" fn bex_top() -> bex_nid_t {
    bex_nid_t { nid: I._to_u64() }
}

#[no_mangle]
pub extern "C" fn bex_bot() -> bex_nid_t {
    bex_nid_t { nid: O._to_u64() }
}

#[no_mangle]
pub extern "C" fn bex_ithvar(vid: bex_vid_t) -> bex_nid_t {
    bex_nid_t { nid: NID::from_vid(VID::var(vid.vid))._to_u64() }
}

#[no_mangle]
pub extern "C" fn bex_bdd_and(bdd: *mut bex_bdd_t, a: bex_nid_t, b: bex_nid_t) -> bex_nid_t {
    bex_bdd_op_body!(bdd, and, a, b)
}

#[no_mangle]
pub extern "C" fn bex_bdd_or(bdd: *mut bex_bdd_t, a: bex_nid_t, b: bex_nid_t) -> bex_nid_t {
    bex_bdd_op_body!(bdd, or, a, b)
}

#[no_mangle]
pub extern "C" fn bex_bdd_xor(bdd: *mut bex_bdd_t, a: bex_nid_t, b: bex_nid_t) -> bex_nid_t {
    bex_bdd_op_body!(bdd, xor, a, b)
}

#[no_mangle]
pub extern "C" fn bex_bdd_ite(bdd: *mut bex_bdd_t, i: bex_nid_t, t: bex_nid_t, e: bex_nid_t) -> bex_nid_t {
    bex_bdd_op_body!(bdd, ite, i, t, e)
}

#[no_mangle]
pub extern "C" fn bex_ast_and(ast: *mut bex_ast_t, a: bex_nid_t, b: bex_nid_t) -> bex_nid_t {
    bex_ast_op_body!(ast, and, a, b)
}

#[no_mangle]
pub extern "C" fn bex_ast_or(ast: *mut bex_ast_t, a: bex_nid_t, b: bex_nid_t) -> bex_nid_t {
    bex_ast_op_body!(ast, or, a, b)
}

#[no_mangle]
pub extern "C" fn bex_ast_xor(ast: *mut bex_ast_t, a: bex_nid_t, b: bex_nid_t) -> bex_nid_t {
    bex_ast_op_body!(ast, xor, a, b)
}

#[no_mangle]
pub extern "C" fn bex_ast_ite(ast: *mut bex_ast_t, i: bex_nid_t, t: bex_nid_t, e: bex_nid_t) -> bex_nid_t {
    bex_ast_op_body!(ast, ite, i, t, e)
}

#[no_mangle]
pub extern "C" fn bex_not(n: bex_nid_t) -> bex_nid_t {
    ffi_guard(ffi_nid_default(), move || {
        let nid = NID::_from_u64(n.nid);
        bex_nid_t { nid: (!nid)._to_u64() }
    })
}

#[no_mangle]
pub extern "C" fn bex_bdd_node_count(bdd: *mut bex_bdd_t, n: bex_nid_t) -> u64 {
    with_bdd_ref(bdd, ffi_u64_default(), |base| {
        let nid = NID::_from_u64(n.nid);
        base.node_count(nid) as u64
    })
}

#[no_mangle]
pub extern "C" fn bex_bdd_solution_count(bdd: *mut bex_bdd_t, n: bex_nid_t) -> u64 {
    ffi_guard(ffi_u64_default(), move || unsafe {
        let Some(bdd_ref) = bdd.as_ref() else { return ffi_u64_default() };
        let base_ptr = bdd_ref.base as *mut Arc<Mutex<BddBase>>;
        let Some(base_arc) = base_ptr.as_ref() else { return ffi_u64_default() };
        let Ok(mut base) = base_arc.lock() else { return ffi_u64_default() };
        let nid = NID::_from_u64(n.nid);
        base.solution_count(nid)
    })
}

#[no_mangle]
pub extern "C" fn bex_swap_new() -> *mut bex_swap_t {
    let base = Box::into_raw(Box::new(Arc::new(Mutex::new(SwapSolver::new()))));
    Box::into_raw(Box::new(bex_swap_t {
        base: base as *mut std::ffi::c_void,
    }))
}

#[no_mangle]
pub extern "C" fn bex_swap_free(swap: *mut bex_swap_t) {
    if !swap.is_null() {
        unsafe {
            let base_ptr = (*swap).base as *mut Arc<Mutex<SwapSolver>>;
            drop(Box::from_raw(base_ptr));
            drop(Box::from_raw(swap));
        }
    }
}

#[no_mangle]
pub extern "C" fn bex_subsolve(ast: *mut bex_ast_t, bdd: *mut bex_bdd_t, n: bex_nid_t) -> bex_nid_t {
    ffi_guard(ffi_nid_default(), move || unsafe {
        let Some(ast_ref) = ast.as_ref() else { return ffi_nid_default() };
        let Some(bdd_ref) = bdd.as_ref() else { return ffi_nid_default() };
        let ast_ptr = ast_ref.base as *mut Arc<Mutex<ASTBase>>;
        let bdd_ptr = bdd_ref.base as *mut Arc<Mutex<BddBase>>;
        let Some(ast_arc) = ast_ptr.as_ref() else { return ffi_nid_default() };
        let Some(bdd_arc) = bdd_ptr.as_ref() else { return ffi_nid_default() };
        let Ok(ast_base) = ast_arc.lock() else { return ffi_nid_default() };
        let Ok(mut bdd_base) = bdd_arc.lock() else { return ffi_nid_default() };
        let nid = NID::_from_u64(n.nid);

        let result_nid = bex_rs::solve::solve(&mut *bdd_base, ast_base.raw_ast(), nid);
        bex_nid_t { nid: result_nid.n._to_u64() }
    })
}

#[no_mangle]
pub extern "C" fn bex_swapsolve(ast: *mut bex_ast_t, swap: *mut bex_swap_t, n: bex_nid_t) -> bex_nid_t {
    ffi_guard(ffi_nid_default(), move || unsafe {
        let Some(ast_ref) = ast.as_ref() else { return ffi_nid_default() };
        let Some(swap_ref) = swap.as_ref() else { return ffi_nid_default() };
        let ast_ptr = ast_ref.base as *mut Arc<Mutex<ASTBase>>;
        let swap_ptr = swap_ref.base as *mut Arc<Mutex<SwapSolver>>;
        let Some(ast_arc) = ast_ptr.as_ref() else { return ffi_nid_default() };
        let Some(swap_arc) = swap_ptr.as_ref() else { return ffi_nid_default() };
        let Ok(ast_base) = ast_arc.lock() else { return ffi_nid_default() };
        let Ok(mut swap_solver) = swap_arc.lock() else { return ffi_nid_default() };
        let nid = NID::_from_u64(n.nid);

        let result_nid = bex_rs::solve::solve(&mut *swap_solver, ast_base.raw_ast(), nid);
        bex_nid_t { nid: result_nid.n._to_u64() }
    })
}

/// Copy the swap solver's result into the given BddBase and return the
/// translated NID.  Needed before calling bex_bdd_node_count /
/// bex_bdd_solution_count on a swap-solver result, because those
/// functions index into `bdd`'s storage rather than the swap solver's.
#[no_mangle]
pub extern "C" fn bex_swap_copy_to_bdd(
    swap: *mut bex_swap_t,
    bdd: *mut bex_bdd_t,
    n: bex_nid_t,
) -> bex_nid_t {
    ffi_guard(ffi_nid_default(), move || unsafe {
        let Some(swap_ref) = swap.as_ref() else { return ffi_nid_default() };
        let Some(bdd_ref)  = bdd.as_ref()  else { return ffi_nid_default() };
        let swap_ptr = swap_ref.base as *mut Arc<Mutex<SwapSolver>>;
        let bdd_ptr  = bdd_ref.base  as *mut Arc<Mutex<BddBase>>;
        let Some(swap_arc) = swap_ptr.as_ref() else { return ffi_nid_default() };
        let Some(bdd_arc)  = bdd_ptr.as_ref()  else { return ffi_nid_default() };
        let Ok(swap_solver) = swap_arc.lock() else { return ffi_nid_default() };
        let Ok(mut bdd_base) = bdd_arc.lock() else { return ffi_nid_default() };
        let nid = NID::_from_u64(n.nid);
        let out = swap_solver.scaffold().copy_to_bdd(&mut bdd_base, &[nid]);
        bex_nid_t { nid: out[0]._to_u64() }
    })
}

#[no_mangle]
pub extern "C" fn bex_is_vid(n: bex_nid_t) -> bool {
    ffi_guard(ffi_bool_default(), move || {
        let nid = NID::_from_u64(n.nid);
        nid.is_var()
    })
}

#[no_mangle]
pub extern "C" fn bex_is_lit(n: bex_nid_t) -> bool {
    ffi_guard(ffi_bool_default(), move || {
        let nid = NID::_from_u64(n.nid);
        nid.is_lit()
    })
}

#[no_mangle]
pub extern "C" fn bex_is_const(n: bex_nid_t) -> bool {
    ffi_guard(ffi_bool_default(), move || {
        let nid = NID::_from_u64(n.nid);
        nid.is_const()
    })
}

#[no_mangle]
pub extern "C" fn bex_is_ast(n: bex_nid_t) -> bool {
    ffi_guard(ffi_bool_default(), move || {
        let nid = NID::_from_u64(n.nid);
        nid.is_ixn()
    })
}

#[no_mangle]
pub extern "C" fn bex_ast_len(ast: *mut bex_ast_t) -> usize {
    with_ast_ref(ast, ffi_usize_default(), |base| {
        base.raw_ast().len()
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn null_bdd_handle_returns_default_values() {
        let n = bex_bdd_and(std::ptr::null_mut(), bex_top(), bex_bot());
        assert_eq!(n.nid, O._to_u64());
        assert_eq!(bex_bdd_node_count(std::ptr::null_mut(), bex_top()), 0);
        assert_eq!(bex_bdd_solution_count(std::ptr::null_mut(), bex_top()), 0);
    }

    #[test]
    fn null_ast_and_swap_handles_return_default_values() {
        let ast_n = bex_ast_and(std::ptr::null_mut(), bex_top(), bex_bot());
        assert_eq!(ast_n.nid, O._to_u64());
        assert_eq!(bex_ast_len(std::ptr::null_mut()), 0);
        let solved = bex_swapsolve(std::ptr::null_mut(), std::ptr::null_mut(), bex_top());
        assert_eq!(solved.nid, O._to_u64());
    }
}
